name: Bug report
description: Report a bug
title: "[BUG] <short description>"
labels:
  - bug
body:
  - type: textarea
    id: background
    attributes:
      label: Describe the bug
      description: Please provide a detailed description of the issue you're seeing.
      placeholder: Description
    validations:
      required: true
