name: Bug report
description: Report a bug
title: "[BUG]"
labels: "bug"
type: "Bug"

body:
  - type: textarea
    id: background
    attributes:
      label: Describe the bug
      description: Please provide the description of issue you're seeing.
      placeholder: Description
    validations:
      required: true
